"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Sparkles, RefreshCw, Lightbulb, Trash2 } from "lucide-react";
import { useAuth } from "@/lib/auth-context";
import {
  listKnowledgeBase,
  generateKnowledgeBase,
  deleteKbEntry,
  listCompetitors,
  type KBEntry,
  type Competitor,
} from "@/lib/api";
import { Navbar } from "@/components/Navbar";
import { formatDate } from "@/lib/utils";

function formatMonth(monthStr: string): string {
  if (!monthStr) return monthStr;
  const [year, month] = monthStr.split("-");
  const date = new Date(Number(year), Number(month) - 1, 1);
  return date.toLocaleString("en-IN", { month: "long", year: "numeric" });
}

// ---------------------------------------------------------------------------
// Shared sub-components
// ---------------------------------------------------------------------------

function BulletList({
  items,
  bulletClass = "bg-slate-400",
}: {
  items: string[] | undefined;
  bulletClass?: string;
}) {
  if (!items || items.length === 0) {
    return <p className="text-sm text-slate-400 italic">None reported.</p>;
  }
  return (
    <ul className="space-y-1">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2 text-sm text-slate-700">
          <span className={`mt-1.5 w-1.5 h-1.5 rounded-full shrink-0 ${bulletClass}`} />
          {item}
        </li>
      ))}
    </ul>
  );
}

// ---------------------------------------------------------------------------
// New-format entry card
// ---------------------------------------------------------------------------

function NewFormatEntry({
  entry,
  onDelete,
}: {
  entry: KBEntry;
  onDelete: (id: number) => void;
}) {
  const [confirming, setConfirming] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const c = entry.content;
  const isNewFormat =
    Array.isArray(c.pr) ||
    Array.isArray(c.newsletter) ||
    Array.isArray(c.web_activity) ||
    Array.isArray(c.social_media);

  if (!isNewFormat) {
    return <LegacyFormatEntry entry={entry} onDelete={onDelete} />;
  }

  async function handleDelete() {
    setDeleting(true);
    try {
      await deleteKbEntry(entry.id);
      onDelete(entry.id);
    } finally {
      setDeleting(false);
      setConfirming(false);
    }
  }

  return (
    <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
      {/* Card header */}
      <div className="px-5 py-4 border-b border-slate-100">
        <div className="flex items-start justify-between gap-4">
          <div>
            <h2 className="text-base font-semibold text-slate-900">
              {entry.competitor_name}
              <span className="text-slate-400 font-normal"> — </span>
              {formatMonth(entry.month)}
            </h2>
            <p className="text-xs text-slate-400 mt-0.5">
              Generated by {entry.generated_by}
            </p>
          </div>
          {/* Delete controls */}
          {confirming ? (
            <div className="flex items-center gap-2 shrink-0">
              <span className="text-xs text-slate-500">Delete this entry?</span>
              <button
                onClick={handleDelete}
                disabled={deleting}
                className="px-2.5 py-1 text-xs font-medium bg-red-600 text-white rounded-md hover:bg-red-700 disabled:opacity-60 transition-colors"
              >
                {deleting ? "Deleting…" : "Yes, delete"}
              </button>
              <button
                onClick={() => setConfirming(false)}
                className="px-2.5 py-1 text-xs font-medium text-slate-600 bg-slate-100 rounded-md hover:bg-slate-200 transition-colors"
              >
                Cancel
              </button>
            </div>
          ) : (
            <button
              onClick={() => setConfirming(true)}
              className="p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded-md transition-colors shrink-0"
              title="Delete entry"
            >
              <Trash2 size={15} />
            </button>
          )}
        </div>
      </div>

      {/* Executive summary */}
      {c.executive_summary && (
        <div className="px-5 py-4 border-b border-slate-100">
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">
            Executive Summary
          </p>
          <p className="text-sm text-slate-800 leading-relaxed">{c.executive_summary}</p>
        </div>
      )}

      {/* 4-section grid */}
      <div className="px-5 py-4 grid grid-cols-1 md:grid-cols-2 gap-6 border-b border-slate-100">
        {/* PR & News */}
        <div>
          <p className="text-xs font-semibold text-blue-600 uppercase tracking-wide mb-2">
            Press Release & News
          </p>
          <BulletList items={c.pr} bulletClass="bg-blue-400" />
        </div>

        {/* Newsletter */}
        <div>
          <p className="text-xs font-semibold text-green-600 uppercase tracking-wide mb-2">
            Newsletter
          </p>
          <BulletList items={c.newsletter} bulletClass="bg-green-500" />
        </div>

        {/* Web Activity */}
        <div>
          <p className="text-xs font-semibold text-amber-600 uppercase tracking-wide mb-2">
            Web Activity
          </p>
          <BulletList items={c.web_activity} bulletClass="bg-amber-500" />
        </div>

        {/* Social Media */}
        <div>
          <p className="text-xs font-semibold text-purple-600 uppercase tracking-wide mb-2">
            Social Media
          </p>
          <BulletList items={c.social_media} bulletClass="bg-purple-500" />
        </div>
      </div>

      {/* Suggestions */}
      {(c.suggestions?.length ?? 0) > 0 && (
        <div className="px-5 py-4 border-b border-slate-100">
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-3 flex items-center gap-1.5">
            <Lightbulb size={11} className="text-teal-500" />
            Suggestions
          </p>
          <div className="flex flex-wrap gap-2">
            {c.suggestions!.map((s, i) => (
              <span
                key={i}
                className="inline-flex items-center gap-1.5 bg-teal-50 text-teal-800 border border-teal-200 rounded-lg px-3 py-1.5 text-xs font-medium leading-snug max-w-xs"
              >
                <Lightbulb size={10} className="text-teal-500 shrink-0" />
                {s}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Card footer */}
      <div className="px-5 py-3 bg-slate-50 border-t border-slate-100">
        <p className="text-xs text-slate-400">
          Generated on {formatDate(entry.generated_at)}
        </p>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Legacy-format entry card (collapsible sections — preserved from old page)
// ---------------------------------------------------------------------------

function LegacyFormatEntry({
  entry,
  onDelete,
}: {
  entry: KBEntry;
  onDelete: (id: number) => void;
}) {
  const [open, setOpen] = useState<Record<string, boolean>>({});
  const [confirming, setConfirming] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const c = entry.content;
  const keyBase = `${entry.id}`;

  async function handleDelete() {
    setDeleting(true);
    try {
      await deleteKbEntry(entry.id);
      onDelete(entry.id);
    } finally {
      setDeleting(false);
      setConfirming(false);
    }
  }

  function toggle(k: string) {
    setOpen((prev) => ({ ...prev, [k]: !prev[k] }));
  }

  function Section({
    title,
    sKey,
    children,
  }: {
    title: string;
    sKey: string;
    children: React.ReactNode;
  }) {
    const isOpen = open[sKey] ?? false;
    return (
      <div className="border-t border-slate-100">
        <button
          onClick={() => toggle(sKey)}
          className="flex items-center gap-2 w-full px-5 py-3 text-left hover:bg-slate-50 transition-colors"
        >
          <span
            className={`w-3 h-3 flex items-center justify-center text-slate-400 text-xs transition-transform ${isOpen ? "rotate-90" : ""}`}
          >
            ▶
          </span>
          <span className="text-sm font-medium text-slate-700">{title}</span>
        </button>
        {isOpen && <div className="px-5 pb-4">{children}</div>}
      </div>
    );
  }

  return (
    <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
      <div className="px-5 py-4 border-b border-slate-100">
        <div className="flex items-start justify-between gap-4">
          <div>
            <h2 className="text-base font-semibold text-slate-900">
              {entry.competitor_name}
              <span className="text-slate-400 font-normal"> — </span>
              {formatMonth(entry.month)}
            </h2>
            <p className="text-xs text-slate-400 mt-0.5">
              Generated by {entry.generated_by}
            </p>
          </div>
          {confirming ? (
            <div className="flex items-center gap-2 shrink-0">
              <span className="text-xs text-slate-500">Delete this entry?</span>
              <button
                onClick={handleDelete}
                disabled={deleting}
                className="px-2.5 py-1 text-xs font-medium bg-red-600 text-white rounded-md hover:bg-red-700 disabled:opacity-60 transition-colors"
              >
                {deleting ? "Deleting…" : "Yes, delete"}
              </button>
              <button
                onClick={() => setConfirming(false)}
                className="px-2.5 py-1 text-xs font-medium text-slate-600 bg-slate-100 rounded-md hover:bg-slate-200 transition-colors"
              >
                Cancel
              </button>
            </div>
          ) : (
            <button
              onClick={() => setConfirming(true)}
              className="p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded-md transition-colors shrink-0"
              title="Delete entry"
            >
              <Trash2 size={15} />
            </button>
          )}
        </div>
      </div>

      <div className="px-5 py-4">
        <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">
          Executive Summary
        </p>
        <p className="text-sm text-slate-800 leading-relaxed">
          {c.executive_summary || (
            <span className="text-slate-400 italic">No summary available.</span>
          )}
        </p>
      </div>

      <Section title="Key Developments" sKey={`${keyBase}-key`}>
        <BulletList items={c.key_developments} />
      </Section>
      <Section title="Product Launches" sKey={`${keyBase}-product`}>
        <BulletList items={c.product_launches} />
      </Section>
      <Section title="News Coverage" sKey={`${keyBase}-news`}>
        <BulletList items={c.news_coverage} />
      </Section>
      <Section title="Hiring Trends" sKey={`${keyBase}-hiring`}>
        <p className="text-sm text-slate-700 leading-relaxed">
          {c.hiring_trends || (
            <span className="text-slate-400 italic">No data available.</span>
          )}
        </p>
      </Section>
      <Section title="Social Media Highlights" sKey={`${keyBase}-social`}>
        <p className="text-sm text-slate-700 leading-relaxed">
          {c.social_media_highlights || (
            <span className="text-slate-400 italic">No data available.</span>
          )}
        </p>
      </Section>
      <Section title="Competitive Intelligence" sKey={`${keyBase}-ci`}>
        <p className="text-sm text-slate-700 leading-relaxed">
          {c.competitive_intelligence || (
            <span className="text-slate-400 italic">No data available.</span>
          )}
        </p>
      </Section>

      <div className="px-5 py-3 bg-slate-50 border-t border-slate-100">
        <p className="text-xs text-slate-400">
          Generated on {formatDate(entry.generated_at)}
        </p>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default function KnowledgeBasePage() {
  const { user, loading } = useAuth();
  const router = useRouter();

  const [entries, setEntries] = useState<KBEntry[]>([]);
  const [competitors, setCompetitors] = useState<Competitor[]>([]);
  const [competitorId, setCompetitorId] = useState<number | undefined>(undefined);
  const [fetching, setFetching] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [generateError, setGenerateError] = useState<string | null>(null);
  const [generateSuccess, setGenerateSuccess] = useState(false);
  const [selectedMonth, setSelectedMonth] = useState<string | null>(null);

  useEffect(() => {
    if (!loading && !user) { router.replace("/login"); return; }
    if (!loading && user?.role !== "admin") { router.replace("/"); return; }
  }, [user, loading, router]);

  useEffect(() => {
    if (user?.role !== "admin") return;
    listCompetitors().then(setCompetitors).catch(() => {});
  }, [user]);

  useEffect(() => {
    if (user?.role !== "admin") return;
    setFetching(true);
    listKnowledgeBase(competitorId)
      .then((data) => {
        setEntries(data);
        // Default-select the most recent month
        if (data.length > 0) {
          const months = Array.from(new Set(data.map((e) => e.month))).sort((a, b) =>
            b.localeCompare(a)
          );
          setSelectedMonth((prev) => prev ?? months[0]);
        }
      })
      .catch(() => setEntries([]))
      .finally(() => setFetching(false));
  }, [user, competitorId]);

  function handleDeleted(id: number) {
    setEntries((prev) => prev.filter((e) => e.id !== id));
  }

  async function handleGenerate() {
    setGenerating(true);
    setGenerateError(null);
    setGenerateSuccess(false);
    try {
      await generateKnowledgeBase(competitorId);
      setGenerateSuccess(true);
      const updated = await listKnowledgeBase(competitorId);
      setEntries(updated);
      setTimeout(() => setGenerateSuccess(false), 4000);
    } catch (err: unknown) {
      setGenerateError(err instanceof Error ? err.message : "Generation failed");
    } finally {
      setGenerating(false);
    }
  }

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="w-5 h-5 border-2 border-blue-600 border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (!user || user.role !== "admin") return null;

  // Derive sorted unique months
  const allMonths = Array.from(new Set(entries.map((e) => e.month))).sort((a, b) =>
    b.localeCompare(a)
  );

  // Entries filtered by selected month
  const displayed = entries
    .filter((e) => !selectedMonth || e.month === selectedMonth)
    .sort((a, b) => a.competitor_name.localeCompare(b.competitor_name));

  return (
    <div className="flex min-h-screen">
      <Navbar />

      <main className="flex-1 p-8 overflow-y-auto">
        <div className="max-w-4xl mx-auto">
          {/* Page header */}
          <div className="flex items-start justify-between mb-6">
            <div>
              <h1 className="text-2xl font-bold text-slate-900">Knowledge Base</h1>
              <p className="text-sm text-slate-500 mt-1">
                Monthly competitive intelligence summaries
              </p>
            </div>
            <button
              onClick={handleGenerate}
              disabled={generating}
              className="flex items-center gap-2 px-4 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:opacity-60 transition-colors"
            >
              {generating ? (
                <>
                  <RefreshCw size={14} className="animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles size={14} />
                  Generate
                </>
              )}
            </button>
          </div>

          {/* Feedback banners */}
          {generateSuccess && (
            <div className="mb-4 px-4 py-3 bg-green-50 border border-green-200 rounded-lg text-sm text-green-700">
              Knowledge base entries generated successfully for the current month.
            </div>
          )}
          {generateError && (
            <div className="mb-4 px-4 py-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700">
              {generateError}
            </div>
          )}

          {/* Competitor filter */}
          <div className="flex items-center gap-3 mb-5">
            <label className="text-sm font-medium text-slate-600">Filter by competitor:</label>
            <select
              value={competitorId ?? ""}
              onChange={(e) =>
                setCompetitorId(e.target.value ? Number(e.target.value) : undefined)
              }
              className="border border-slate-200 rounded-lg px-3 py-2 text-sm text-slate-700 bg-white focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="">All</option>
              {competitors.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.name}
                </option>
              ))}
            </select>
          </div>

          {/* Month selector tabs */}
          {allMonths.length > 0 && (
            <div className="flex items-center gap-2 flex-wrap mb-6">
              {allMonths.map((m) => (
                <button
                  key={m}
                  onClick={() => setSelectedMonth(m)}
                  className={`px-3 py-1.5 rounded-full text-sm font-medium transition-colors ${
                    selectedMonth === m
                      ? "bg-blue-600 text-white shadow-sm"
                      : "bg-slate-100 text-slate-600 hover:bg-slate-200"
                  }`}
                >
                  {formatMonth(m)}
                </button>
              ))}
            </div>
          )}

          {/* Content */}
          {fetching ? (
            <div className="flex items-center justify-center py-24">
              <div className="w-6 h-6 border-2 border-blue-600 border-t-transparent rounded-full animate-spin" />
            </div>
          ) : entries.length === 0 ? (
            <div className="py-24 text-center border border-dashed border-slate-200 rounded-xl">
              <p className="text-sm text-slate-500 font-medium">No knowledge base entries yet.</p>
              <p className="text-sm text-slate-400 mt-1">
                Click Generate to create entries for the current month.
              </p>
            </div>
          ) : displayed.length === 0 ? (
            <div className="py-16 text-center border border-dashed border-slate-200 rounded-xl">
              <p className="text-sm text-slate-400">
                No entries for {selectedMonth ? formatMonth(selectedMonth) : "the selected filters"}.
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              {displayed.map((entry) => (
                <NewFormatEntry key={entry.id} entry={entry} onDelete={handleDeleted} />
              ))}
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
